version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Docker/app.Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    restart: always

  data_fetcher:
    build:
      context: .
      dockerfile: Docker/data_fetcher.Dockerfile
    volumes:
      - .:/app
    restart: always
