name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-macro-report:
    name: Deploy Macro Report App
    runs-on: macro-runner 

    steps:
    - name: Check Docker Installation
      run: sudo docker info || echo "Docker is not available"

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Prune Unused Docker Resources
      run: sudo docker system prune -af

    - name: Pull Macro Report Docker Image
      run: sudo docker pull smokepaus/macro-report:latest

    - name: Stop and Remove Existing Macro Report Container
      run: |
        sudo docker stop macro-report-container || true
        sudo docker rm macro-report-container || true

    - name: Run Macro Report Docker Container
      run: |
        sudo docker run -d -p 80:5000 --name macro-report-container smokepaus/macro-report:latest

    - name: Cleanup Docker
      run: sudo docker system prune -f --volumes

  deploy-data-fetcher:
    name: Deploy Data Fetcher
    runs-on: data-fetcher-runner

    steps:
    - name: Check Docker Installation
      run: sudo docker info || echo "Docker is not available"

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Prune Unused Docker Resources
      run: sudo docker system prune -af

    - name: Pull Data Fetcher Docker Image
      run: sudo docker pull smokepaus/data-fetcher:latest

    - name: Stop and Remove Existing Data Fetcher Container
      run: |
        sudo docker stop data-fetcher-container || true
        sudo docker rm data-fetcher-container || true

    - name: Run Data Fetcher Docker Container
      run: |
        sudo docker run --name data-fetcher-container -d smokepaus/data-fetcher:latest

