name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Prune Unused Docker Resources
      run: docker system prune -af

    # Build and Push Macro Report Image
    - name: Build Macro Report Docker Image
      run: docker build -t smokepaus/macro-report:latest -f Docker/app.Dockerfile .

    - name: Push Macro Report Docker Image
      run: docker push smokepaus/macro-report:latest

    # Build and Push Data Fetcher Image
    - name: Build Data Fetcher Docker Image
      run: docker build -t smokepaus/data-fetcher:latest -f Docker/data-fetcher.Dockerfile .

    - name: Push Data Fetcher Docker Image
      run: docker push smokepaus/data-fetcher:latest

    - name: Cleanup Docker
      run: docker system prune -f --volumes
